"""
LFP 扩胞掺杂构型生成器 v4（文献优化版）
======================================
根据磷酸铁锂掺杂文献优化设计，覆盖有实验验证的浓度区间。

超胞参数:
  - 超胞规模: 8×6×3 = 48 倍原胞
  - n_total = 4 × 8 × 6 × 3 = 576 (Fe位点数 / Li位点数 / P位点数)
  - n 值范围: 1 ~ 10
  - 浓度范围: 0.174% ~ 1.736%
  - 浓度点数: 10 个, 步长 0.174%

  这个范围与文献中实际掺杂浓度区间（0.1%~2%）高度吻合：
  - 产业化 Ti 掺杂: ~0.5%~2%
  - 研究文献: 0.1%~5%（主要集中在 <3%）

掺杂配置（基于文献调研优化）:
  - Li位掺杂(5种): Na, Mg, Al, Ti, W
    * Na: 减小Li+迁移能垒，提高离子电导率
    * Mg: 稳定框架，提高循环稳定性
    * Al: 稳定结构，抑制相变
    * Ti: 产业化主流，降低极化，抑制晶粒生长
    * W:  2002年Chung等人的开创性工作(W6+)，提高8个数量级

  - Fe位掺杂(13种): Ti, V, Cr, Mn, Co, Ni, Cu, Zn, Mo, Nb, Er, Y, Nd
    * Ti: 削弱Li-O键，增加晶格体积
    * V:  多种氧化态，可替代Fe/P位
    * Cr: 提高导电性（注意：Li位Cr无法扩散）
    * Mn: 常用掺杂，提高稳定性
    * Co: 常用掺杂，优化电子结构
    * Ni: 常用掺杂，改善电化学性能
    * Cu: 提高电子导电性
    * Zn: 拓宽Li+传输通道
    * Mo: 多种氧化态，稳定结构
    * Nb: 2002年开创性工作，提高8个数量级
    * Er, Y, Nd: 稀土掺杂，电导率提高4个数量级（p型掺杂）

  - P位掺杂(2种): Si, S
    * Si: Si+F共掺可提高2-3个数量级
    * S:  改善离子扩散

预期构型数:
  - Li位: 5 × 10 × 3 = 150
  - Fe位: 13 × 10 × 3 = 390
  - P位:  2 × 10 × 3 = 60
  - 合计: 600 个构型（相比v3减少5倍，计算时间大幅缩短）

用法:
    conda run -n lfp_doping python generate_lfp_dopants_v4.py
"""

import os
import sys
import json
import time
import random
import math
import numpy as np
import multiprocessing as mp
from collections import Counter

# ============================================================================
# 配置参数
# ============================================================================

# 优化后的超胞：8×6×3，覆盖文献浓度区间 0.17%~1.74%
SUPERCELL = (8, 6, 3)   # nx, ny, nz
NX, NY, NZ = SUPERCELL

N_TOTAL = 4 * NX * NY * NZ  # = 576 (Fe位点数 / Li位点数 / P位点数)
N_MIN = 1                     # n=1 → 0.174%
N_MAX = 10                    # n=10 → 1.736%
CONFIGS_PER_CONC = 3         # 每个浓度点的随机构型数

# 文献优化后的掺杂元素
DOPING_CONFIG = {
    # Li位掺杂（5种，有产业化或文献支持）
    "Li": {"dopants": ["Na", "Mg", "Al", "Ti", "W"]},
    # Fe位掺杂（13种，文献研究热点 + 稀土）
    "Fe": {"dopants": ["Ti", "V", "Cr", "Mn", "Co", "Ni", "Cu", "Zn", "Mo", "Nb", "Er", "Y", "Nd"]},
    # P位掺杂（2种，Si/F共掺是主流方向）
    "P":  {"dopants": ["Si", "S"]},
}

OUTPUT_DIR = None

# ============================================================================
# POSCAR 写入
# ============================================================================

def write_poscar_fast(filepath, lattice, species_ordered, species_copy, coords, atom_counts):
    with open(filepath, "w") as f:
        f.write("Generated by LFP supercell v4 (Literature-Optimized)\n")
        f.write("  1.0\n")
        for row in lattice:
            f.write("  {0:15.10f}  {1:15.10f}  {2:15.10f}\n".format(row[0], row[1], row[2]))
        f.write("  " + "  ".join(species_ordered) + "\n")
        f.write("  " + "  ".join(str(c) for c in atom_counts) + "\n")
        f.write("Cartesian\n")
        # 按物种分组写坐标（species_copy[i] 对应 coords[i]）
        sp_to_coords = {}
        for sp in species_ordered:
            sp_to_coords[sp] = []
        for i, sp_i in enumerate(species_copy):
            sp_to_coords[sp_i].append(coords[i])
        for sp in species_ordered:
            for c in sp_to_coords[sp]:
                f.write("  {0:15.10f}  {1:15.10f}  {2:15.10f}\n".format(c[0], c[1], c[2]))


def get_concentration(n):
    return n / N_TOTAL * 100


def generate_config_id(site, dopant, n, config_idx):
    # 用 ppm 编码：n/n_total * 1e6 -> 唯一整数
    conc_ppm = round(n / N_TOTAL * 1e6)  # 如 1736 ppm = 0.1736%
    return f"LFP_{site}={dopant}_x{conc_ppm:05d}_n{n}_c{config_idx}"


# ============================================================================
# 多进程生成
# ============================================================================

def generate_batch(batch_args):
    batch = batch_args["batch"]
    lattice = batch_args["lattice"]
    supercell_species_arr = batch_args["supercell_species_arr"]
    supercell_coords = batch_args["supercell_coords"]
    indices = batch_args["indices"]
    output_dir = batch_args["output_dir"]
    poscar_dir = batch_args["poscar_dir"]

    generated = 0
    skipped = 0
    results = []

    for item in batch:
        site_name = item["site_name"]
        dopant = item["dopant"]
        n = item["n"]
        config_idx = item["config_idx"]
        replace_indices = item["replace_indices"]

        try:
            conc = get_concentration(n)
            config_id = generate_config_id(site_name, dopant, n, config_idx)

            species_copy = supercell_species_arr.copy()
            for idx in replace_indices:
                species_copy[idx] = dopant

            species_count = Counter(species_copy)
            species_ordered = sorted(species_count.keys())
            atom_counts = [species_count[s] for s in species_ordered]

            poscar_path = os.path.join(poscar_dir, f"{config_id}.poscar")
            write_poscar_fast(
                poscar_path, lattice, species_ordered,
                species_copy, supercell_coords, atom_counts
            )

            results.append({
                "config_id": config_id,
                "doping_site": site_name,
                "dopant": dopant,
                "n_dopant_atoms": n,
                "concentration_pct": conc,
                "supercell": list(SUPERCELL),
                "formula": "".join(f"{s}{c}" for s, c in zip(species_ordered, atom_counts)),
                "n_atoms": len(species_copy),
                "poscar_path": os.path.relpath(poscar_path, output_dir),
                "lattice_a": float(np.linalg.norm(lattice[0])),
                "lattice_b": float(np.linalg.norm(lattice[1])),
                "lattice_c": float(np.linalg.norm(lattice[2])),
            })
            generated += 1
        except Exception:
            skipped += 1

    return generated, skipped, results


# ============================================================================
# 主函数
# ============================================================================

def main():
    global OUTPUT_DIR
    t_start = time.time()

    OUTPUT_DIR = os.path.join(
        os.path.dirname(os.path.abspath(__file__)),
        "lfp_dopant_configs_v4"
    )
    poscar_dir = os.path.join(OUTPUT_DIR, "poscar_files")
    os.makedirs(poscar_dir, exist_ok=True)
    os.makedirs(os.path.join(OUTPUT_DIR, "metadata"), exist_ok=True)

    n_workers = max(1, mp.cpu_count() - 1)
    print(f"使用 {n_workers} 个 CPU 核心")

    print("=" * 70)
    print("LFP 扩胞掺杂构型生成器 v4（文献优化版）")
    print("=" * 70)
    print("\n超胞配置:")
    print("  超胞规模: {0}×{1}×{2} = {3} 倍原胞".format(NX, NY, NZ, NX*NY*NZ))
    print("  n_total: {0} (Fe/Li/P 位点数)".format(N_TOTAL))
    print("  n 值范围: {0} ~ {1}".format(N_MIN, N_MAX))
    print("  浓度范围: {0:.4f}% ~ {1:.4f}%".format(
        get_concentration(N_MIN), get_concentration(N_MAX)))
    print("  浓度点数: {0} 个, 步长: {1:.4f}%".format(
        N_MAX - N_MIN + 1, get_concentration(1)))
    print("  每浓度随机构型数: {0}".format(CONFIGS_PER_CONC))

    print("\n掺杂元素（基于文献优化）:")
    for site in ["Li", "Fe", "P"]:
        dopants = DOPING_CONFIG[site]["dopants"]
        print("  {0}位({1}种): {2}".format(site, len(dopants), ", ".join(dopants)))

    expected = (N_MAX - N_MIN + 1) * CONFIGS_PER_CONC
    total_expected = sum(len(DOPING_CONFIG[s]["dopants"]) for s in DOPING_CONFIG) * expected
    print("\n预期构型数:")
    for site in ["Li", "Fe", "P"]:
        n_configs = len(DOPING_CONFIG[site]["dopants"]) * expected
        print("  {0}位: {1} 构型".format(site, n_configs))
    print("  合计: {0} 构型（相比v3的3000减少{1}倍）".format(
        total_expected, round(3000/total_expected, 1)))

    print("\n文献浓度对比:")
    print("  本次设计: {0:.2f}% ~ {1:.2f}%".format(
        get_concentration(N_MIN), get_concentration(N_MAX)))
    print("  产业化Ti掺杂: ~0.5% ~ 2.0%")
    print("  研究文献主流: 0.1% ~ 5.0%（<3%居多）")
    print("  结论: 本次范围与文献高度吻合 ✓")
    print("=" * 70)

    # 加载原始结构
    print("\n[1/4] 加载原始 LiFePO4 结构...")
    from pymatgen.core import Structure
    cif_path = os.path.join(
        os.path.dirname(os.path.abspath(__file__)),
        "alignn", "models", "LiFePO4.cif"
    )
    structure = Structure.from_file(cif_path)
    print("    原始: {0}, {1} 原子".format(
        structure.composition.reduced_formula, len(structure)))

    # 创建超胞
    print("\n[2/4] 创建 {0}×{1}×{2} 超胞...".format(NX, NY, NZ))
    supercell = structure.copy()
    supercell.make_supercell([NX, NY, NZ])
    print("    超胞原子数: {0}".format(len(supercell)))

    # 提取数据
    lattice = supercell.lattice.matrix.copy()
    supercell_coords = supercell.cart_coords.copy()
    supercell_species_str = [str(s) for s in supercell.species]
    supercell_species_arr = np.array([
        s.replace("+", "").replace("-", "").replace("2", "").replace("3", "").replace("5", "")
        for s in supercell_species_str
    ])

    # 分类原子位置
    fe_idx = np.where(supercell_species_arr == "Fe")[0].tolist()
    li_idx = np.where(supercell_species_arr == "Li")[0].tolist()
    p_idx  = np.where(supercell_species_arr == "P")[0].tolist()
    site_indices = {"Fe": fe_idx, "Li": li_idx, "P": p_idx}
    print("    Fe位: {0}, Li位: {1}, P位: {2}".format(
        len(fe_idx), len(li_idx), len(p_idx)))

    # 生成任务
    print("\n[3/4] 生成构型任务...")
    task_counter = 0
    all_tasks = []
    for site_name, indices in site_indices.items():
        dopants = DOPING_CONFIG[site_name]["dopants"]
        for dopant in dopants:
            for n in range(N_MIN, N_MAX + 1):
                for config_idx in range(1, CONFIGS_PER_CONC + 1):
                    # 每个 config 用不同的 seed（基于任务计数器，保证唯一性）
                    task_counter += 1
                    rng = random.Random(42 + task_counter)
                    replace_indices = rng.sample(indices, n)
                    all_tasks.append({
                        "site_name": site_name, "dopant": dopant,
                        "n": n, "config_idx": config_idx,
                        "replace_indices": replace_indices,
                    })

    total_tasks = len(all_tasks)
    print("    总任务数: {0}".format(total_tasks))

    # 分批
    batch_size = 100
    batches = []
    for i in range(0, total_tasks, batch_size):
        batch = all_tasks[i:i+batch_size]
        batches.append({
            "batch": batch,
            "lattice": lattice,
            "supercell_species_arr": supercell_species_arr,
            "supercell_coords": supercell_coords,
            "indices": site_indices,
            "output_dir": OUTPUT_DIR,
            "poscar_dir": poscar_dir,
        })

    print(f"    分为 {len(batches)} 批，每批 {batch_size} 个任务")
    print("\n开始生成...")

    t_gen = time.time()
    total_gen = 0
    total_skip = 0
    all_meta = []

    with mp.Pool(processes=n_workers) as pool:
        for i, (g, s, m) in enumerate(pool.imap_unordered(generate_batch, batches)):
            total_gen += g
            total_skip += s
            all_meta.extend(m)
            if (i + 1) % 5 == 0 or (i + 1) == len(batches):
                pct = (i + 1) / len(batches) * 100
                print(f"      进度: {pct:5.1f}% ({i+1}/{len(batches)} 批, {total_gen} 个)")

    print(f"\n    完成! 成功: {total_gen}, 跳过: {total_skip}")

    # 保存
    print("\n[4/4] 保存结果...")
    by_site = {}
    by_dopant = {}
    for m in all_meta:
        s, d = m["doping_site"], m["dopant"]
        by_site.setdefault(s, {"count": 0, "dopants": []})
        by_site[s]["count"] += 1
        if d not in by_site[s]["dopants"]:
            by_site[s]["dopants"].append(d)
        by_dopant.setdefault(d, {"count": 0, "site": s})
        by_dopant[d]["count"] += 1

    summary = {
        "generation_info": {
            "timestamp": time.strftime("%Y-%m-%d %H:%M:%S"),
            "version": "4.0",
            "note": "文献优化版，覆盖有实验验证的掺杂浓度区间",
            "supercell": {"nx": NX, "ny": NY, "nz": NZ, "multiplier": NX*NY*NZ},
            "n_total": N_TOTAL,
            "n_range": {"min": N_MIN, "max": N_MAX},
            "concentration_range": {
                "min": get_concentration(N_MIN),
                "max": get_concentration(N_MAX),
            },
            "concentration_step_pct": get_concentration(1),
            "configs_per_concentration": CONFIGS_PER_CONC,
            "n_workers": n_workers,
            "generation_time_seconds": round(time.time() - t_gen, 1),
        },
        "literature_reference": {
            "concentration_range_design": "0.17% ~ 1.74%",
            "literature_range": "0.1% ~ 5.0%（<3%居多）",
            "industrial_range": "~0.5% ~ 2.0% (Ti掺杂)",
            "alignment": "高度吻合，有大量文献验证",
        },
        "doping_elements_literature": {
            "Li": {
                "elements": ["Na", "Mg", "Al", "Ti", "W"],
                "note": "Ti是产业化主流，W/Nb是2002年开创性工作"
            },
            "Fe": {
                "elements": ["Ti", "V", "Cr", "Mn", "Co", "Ni", "Cu", "Zn", "Mo", "Nb", "Er", "Y", "Nd"],
                "note": "包含13种元素，其中Er/Y/Nd是稀土掺杂（电导率提高4个数量级）"
            },
            "P": {
                "elements": ["Si", "S"],
                "note": "Si+F共掺可提高2-3个数量级"
            }
        },
        "summary": {
            "total_structures": len(all_meta),
            "fe_sites": len(fe_idx), "li_sites": len(li_idx), "p_sites": len(p_idx),
            "atoms_per_supercell": len(supercell),
        },
        "by_site": by_site,
        "by_dopant": by_dopant,
    }

    with open(os.path.join(OUTPUT_DIR, "summary.json"), "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2, ensure_ascii=False)

    with open(os.path.join(OUTPUT_DIR, "metadata", "doping_library_metadata.json"),
              "w", encoding="utf-8") as f:
        json.dump({"generation_info": summary["generation_info"], "structures": all_meta},
                  f, indent=2, ensure_ascii=False)

    with open(os.path.join(OUTPUT_DIR, "all_config_ids.txt"), "w") as f:
        f.write("\n".join(m["config_id"] for m in all_meta))

    # 统计
    print("\n" + "=" * 70)
    print("生成统计")
    print("=" * 70)
    print("  总构型数: {0}".format(len(all_meta)))
    print("  按位点:")
    for site, info in sorted(by_site.items()):
        print("    {0}位: {1} 构型 ({2}种: {3})".format(
            site, info["count"], len(info["dopants"]), ", ".join(sorted(info["dopants"]))))

    print("\n  浓度序列 ({0:.4f}% ~ {1:.4f}%, 步长 {2:.4f}%):".format(
        get_concentration(N_MIN), get_concentration(N_MAX), get_concentration(1)))
    concs = ["{0:.4f}%".format(get_concentration(n)) for n in range(N_MIN, N_MAX + 1)]
    print("  " + ", ".join(concs))
    print("  共 {0} 个浓度点".format(len(concs)))

    elapsed = time.time() - t_start
    print("\n总耗时: {0:.1f} 秒".format(elapsed))
    poscar_count = len([f for f in os.listdir(poscar_dir) if f.endswith(".poscar")])
    print("POSCAR 文件数: {0}".format(poscar_count))
    print("输出目录: {0}".format(OUTPUT_DIR))

    # 时间预估
    print("\n预测时间预估（基于M5芯片）:")
    time_per_config = 130 * (576/1280)  # 按原子数比例缩放
    total_inferences = len(all_meta) * 8  # 8个模型
    est_hours = total_inferences * time_per_config / 3600
    print("  原子数比例: {0}/{1} = {2:.2f}".format(576, 1280, 576/1280))
    print("  单构型时间: ~{0} 秒".format(round(time_per_config)))
    print("  总推理次数: {0} 构型 × 8 模型 = {1} 次".format(len(all_meta), total_inferences))
    print("  预估总时间: ~{0} 小时 (~{1} 天)".format(round(est_hours), round(est_hours/24, 1)))
    print("=" * 70)


if __name__ == "__main__":
    mp.set_start_method("spawn", force=True)
    main()
